# Welcome to Jekyll!

# Website settings
title: "Luis P.'s Home Page"
description: "Luis P. Prieto's home page including CV, projects, publications and more."
keywords: "LuisPPrieto,lprisan,research,personal"
baseurl: "/"
url: "http://lprisan.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Luis P. Prieto'
  first_name: 'Prieto'
  last_name: 'Luis P.'
  email: 'luis.pablo.prieto@gmail.com'
  facebook_username: 'lprisan'
  github_username: 'lprisan'
  head_img: 'static/img/landing/lprisan.jpg'
  desc: 'I am a learning technologies researcher currently based in Tallinn (Estonia). My main research interests include multimodal teaching analytics, teacher professional development, distributed learning environments, uses of augmented reality and paper computing in education, and lifelong learning.'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'publications'
    i18n: 'nav.publications'
    name: 'Publications'
    tpl: 'publications.html'
    css: ''

  - id: 'projects'
    i18n: 'nav.projects'
    name: 'Projects'
    tpl: 'projects.html'
    css: 'project'

  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'
  - locale: 'es'
    flag: 'static/img/flags/Spain.png'

# blog img path
#img_path: 'http://www.jack003.com/static/img/blog'

# donate
#donate:
#  wechat: 'static/img/pay/wechat.png'
#  alipay: 'static/img/pay/alipay.png'

# comment
#changyan:
#  appid: cysfY7ULn
#  conf: prod_861928934cecb7a18e15bedaed9dae29
#disqus:
#  name: jalpc
#  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
#bshare:
#  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
#ba:
#   uuid: 317acca9ef9255b934e46371e471431d

# google analytics
#ga:
#  id: UA-73784599-1

# growingIO
#gio:
#  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
